#!/usr/bin/env python3
# Copyright (c) 2016-2018 David Preece - davep@polymath.tech, All rights reserved.
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

import logging
from tfnz.cli import base_argparse
from tfnz.location import Location
from tfnz.platforms.silverstripe import SilverStripe

logging.basicConfig(level=logging.INFO)
parser = base_argparse('silverstripe')
parser.add_argument('fqdn', help='The fqdn to publish to')
parser.add_argument('volume', help='The volume (tag) to use for persistent storage')
args = parser.parse_args()

loc = Location()
data_vol = loc.ensure_volume(args.volume + '_data')
sql_vol = loc.ensure_volume(args.volume + '_sql')
silverstripe = SilverStripe(loc, data_vol, sql_vol, args.fqdn,
                            log_callback=lambda _, d: print(d.decode(), end=''))
loc.run()
