#!/usr/bin/env python3
import logging
from tfnz.cli import base_argparse
from tfnz.location import Location
from tfnz.platforms.silverstripe import SilverStripe

logging.basicConfig(level=logging.INFO)
parser = base_argparse('silverstripe')
parser.add_argument('fqdn', help='The fqdn to publish to')
parser.add_argument('volume', help='The volume (tag) to use for persistent storage')
args = parser.parse_args()

loc = Location()
data_vol = loc.ensure_volume(args.volume + '_data')
sql_vol = loc.ensure_volume(args.volume + '_sql')
silverstripe = SilverStripe(loc, data_vol, sql_vol, args.fqdn,
                            log_callback=lambda _, d: print(d.decode(), end=''))
loc.run()
