#!/usr/bin/env python3
import sys
from tfnz.cli import base_argparse
from tfnz.location import Location
from tfnz.components.mail import Mail

parser = base_argparse('mail-server')
parser.add_argument('-s', help='Create ssh server on port 2222', action='store_true')
parser.add_argument('--image', help='Specify an image other than "tfnz/mail"')
parser.add_argument('--dkim', help='Use DKIM', action='store_true')
parser.add_argument('domain', help='The domain name of the mailserver')
parser.add_argument('volume', help='The volume (tag) to use for persistent storage')
parser.add_argument('userfile', help='Name of the file that holds user:password pairs')
args = parser.parse_args()

with open(args.userfile) as f:
    users = f.readlines()

loc = Location(args.location, location_ip=args.local, debug_log=True)
try:
    vol = loc.volume(args.volume)
    m = Mail(args.domain, users, ssh=args.s, dkim=args.dkim, image=args.image)
    m.spawn(loc, vol, log_callback=lambda c, s: sys.stdout.write(s.decode()),
            local_smtp=2525, local_smtps=1465, local_imap=1993)
finally:
    loc.disconnect()
